### ISSUE TITLE
Update session description 2022-05-04, slot 1 + slot 2

### ISSUE THREAD

**Issue by aforemny** [aforemny/fp-hannover#16]
Hi @Marvin, please update [your session's descriptions](https://github.com/aforemny/fp-hannover/blob/master/events/2022-05-25.md) on our website, so that I can announce it on Meetup. :-)

**Comment by CrazyMarvin** [comment]
I skipped the PR by accident and directly pushed the update with https://github.com/aforemny/fp-hannover/commit/40d65806a368e83d57f1a4aa4ed0b0d47dffa382.

**Comment by aforemny** [comment]
@CrazyMarvin That's quite alright. Thank you very much!
